name: Test

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}

    timeout-minutes: 6

    strategy:
      matrix:
        node-version: [16.7.x]
        os: [ubuntu-latest, windows-latest, macos-latest] # mac
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.23.5

      - name: Set node version to ${{ matrix.node_version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}
          cache: "pnpm"

      - name: Install
        run: pnpm i

      - name: Build
        run: pnpm run build

      - name: Test Miniflare@1
        run: pnpm run test:ci:1

      - name: Test Miniflare@2
        run: pnpm run test:ci:2

      - name: Lint
        run: pnpm run lint --if-present

      - name: TypeCheck
        run: pnpm run typecheck
